"""empty message

Revision ID: 1197d9ddd498
Revises: d1454e474ca7
Create Date: 2022-03-16 10:56:46.049517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1197d9ddd498'
down_revision = 'd1454e474ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('properties_profiles_photo_key', 'properties_profiles', type_='unique')
    op.drop_column('properties_profiles', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_profiles', sa.Column('photo', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_unique_constraint('properties_profiles_photo_key', 'properties_profiles', ['photo'])
    # ### end Alembic commands ###
