"""empty message

Revision ID: 6870cb4b22a2
Revises: a9c993dd2cfc
Create Date: 2022-03-12 13:57:37.886961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6870cb4b22a2'
down_revision = 'a9c993dd2cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_profiles', sa.Column('photo_name', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'properties_profiles', ['photo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties_profiles', type_='unique')
    op.drop_column('properties_profiles', 'photo_name')
    # ### end Alembic commands ###
