"""empty message

Revision ID: a9c993dd2cfc
Revises: 
Create Date: 2022-03-11 16:10:48.490867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c993dd2cfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('location', sa.String(length=280), nullable=False),
    sa.Column('num_bath', sa.Integer(), nullable=False),
    sa.Column('num_bed', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties_profiles')
    # ### end Alembic commands ###
