"""empty message

Revision ID: d1454e474ca7
Revises: ddfb3c41e97c
Create Date: 2022-03-12 18:36:28.325741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1454e474ca7'
down_revision = 'ddfb3c41e97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties_profiles', sa.Column('text', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties_profiles', 'text')
    # ### end Alembic commands ###
