"""empty message

Revision ID: ddfb3c41e97c
Revises: 6870cb4b22a2
Create Date: 2022-03-12 15:10:39.056635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfb3c41e97c'
down_revision = '6870cb4b22a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties_profiles', 'type',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties_profiles', 'type',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
